//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputingServices.App.DynamicData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertainSportAbilityTestEvaluationCriteriaSubSports
    {
        public CertainSportAbilityTestEvaluationCriteriaSubSports()
        {
            this.CertainSportAbilityTestEvaluationCriteriaSubSportParametersSets = new HashSet<CertainSportAbilityTestEvaluationCriteriaSubSportParametersSets>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string UnitOfMeasure { get; set; }
        public string DataType { get; set; }
        public string ComparePattern { get; set; }
        public int Sport_Id { get; set; }
    
        public virtual CertainSportAbilityTestEvaluationCriteriaSports CertainSportAbilityTestEvaluationCriteriaSports { get; set; }
        public virtual ICollection<CertainSportAbilityTestEvaluationCriteriaSubSportParametersSets> CertainSportAbilityTestEvaluationCriteriaSubSportParametersSets { get; set; }
    }
}
