//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputingServices.App.DynamicData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertainSportAbilityTestEvaluationCriteriaSports
    {
        public CertainSportAbilityTestEvaluationCriteriaSports()
        {
            this.CertainSportAbilityTestEvaluationCriteriaSportParameters = new HashSet<CertainSportAbilityTestEvaluationCriteriaSportParameters>();
            this.CertainSportAbilityTestEvaluationCriteriaSubSports = new HashSet<CertainSportAbilityTestEvaluationCriteriaSubSports>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CertainSportAbilityTestEvaluationCriteriaSportParameters> CertainSportAbilityTestEvaluationCriteriaSportParameters { get; set; }
        public virtual ICollection<CertainSportAbilityTestEvaluationCriteriaSubSports> CertainSportAbilityTestEvaluationCriteriaSubSports { get; set; }
    }
}
