//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputingServices.App.DynamicData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertainSportAbilityTestEvaluationCriteriaSubSportParameters
    {
        public int Id { get; set; }
        public string OriginalValue { get; set; }
        public int ScoreValue { get; set; }
        public string ScoreLevel { get; set; }
        public int CertainSportAbilityTestEvaluationCriteriaSubSportParametersSet_Id { get; set; }
    
        public virtual CertainSportAbilityTestEvaluationCriteriaSubSportParametersSets CertainSportAbilityTestEvaluationCriteriaSubSportParametersSets { get; set; }
    }
}
