//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputingServices.App.DynamicData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertainSportAbilityTestEvaluationCriteriaSportParameters
    {
        public int Id { get; set; }
        public string Level { get; set; }
        public int Score { get; set; }
        public Nullable<int> AgeMin { get; set; }
        public Nullable<int> AgeMax { get; set; }
        public string Gender { get; set; }
        public int CertainSportAbilityTestEvaluationCriteriaSport_Id { get; set; }
    
        public virtual CertainSportAbilityTestEvaluationCriteriaSports CertainSportAbilityTestEvaluationCriteriaSports { get; set; }
    }
}
