//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputingServices.App.DynamicData.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputingServicesContext : DbContext
    {
        public ComputingServicesContext()
            : base("name=ComputingServicesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CertainSportAbilityTestEvaluationCriteriaSportParameters> CertainSportAbilityTestEvaluationCriteriaSportParameters { get; set; }
        public DbSet<CertainSportAbilityTestEvaluationCriteriaSports> CertainSportAbilityTestEvaluationCriteriaSports { get; set; }
        public DbSet<CertainSportAbilityTestEvaluationCriteriaSubSportParameters> CertainSportAbilityTestEvaluationCriteriaSubSportParameters { get; set; }
        public DbSet<CertainSportAbilityTestEvaluationCriteriaSubSportParametersSets> CertainSportAbilityTestEvaluationCriteriaSubSportParametersSets { get; set; }
        public DbSet<CertainSportAbilityTestEvaluationCriteriaSubSports> CertainSportAbilityTestEvaluationCriteriaSubSports { get; set; }
    }
}
